export const SET_NORMAL_CUSTOMERS_VISIBILITY = 'SET_NORMAL_CUSTOMERS_VISIBILITY';
export const SET_NORMAL_CUSTOMERS_DATA = 'SET_NORMAL_CUSTOMERS_DATA';

export const SET_VIP_CUSTOMERS_VISIBILITY = 'SET_VIP_CUSTOMERS_VISIBILITY';
export const SET_VIP_CUSTOMERS_DATA = 'SET_VIP_CUSTOMERS_DATA';

export const SET_SHOPS_VISIBILITY = 'SET_SHOPS_VISIBILITY';
export const SET_SHOPS_DATA = 'SET_SHOPS_DATA';

export const SET_EMPLOYEES_VISIBILITY = 'SET_EMPLOYEES_VISIBILITY';
export const SET_EMPLOYEES_DATA = 'SET_EMPLOYEES_DATA';

export const SET_MATERIAL_EXPENSES_VISIBILITY = 'SET_MATERIAL_EXPENSES_VISIBILITY';
export const SET_MATERIAL_EXPENSES_DATA = 'SET_MATERIAL_EXPENSES_DATA';

export const SET_SHOP_EXPENSES_VISIBILITY = 'SET_SHOP_EXPENSES_VISIBILITY';
export const SET_SHOP = 'SET_SHOP';
